name: tourpal
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_app_check: ^0.3.2+6
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  
  
  # Authentication
  google_sign_in: ^6.1.4
  
  # BLoC State Management
  provider: ^6.1.1
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5

  # Clean Architecture & Dependency Injection
  get_it: ^8.0.0
  dartz: ^0.10.1

  # UI
  cupertino_icons: ^1.0.2

  # Image picking and permissions
  image_picker: ^1.0.7
  permission_handler: ^12.0.0+1
  flutter_image_compress: ^2.1.0

  # Maps and Location
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.1
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.0.0
  polyline_codec: ^0.1.6
  google_places_flutter: ^2.0.9
  
  # HTTP requests
  http: ^1.1.0

  # Utilities
  intl: ^0.20.2
  uuid: ^4.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  device_info_plus: ^11.4.0
  url_launcher: ^6.2.5
  share_plus: ^11.0.0
  shared_preferences: ^2.2.2
  async: ^2.11.0

  # Notifications
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1

  # UI Components
  multi_select_flutter: ^4.1.3
  firebase_messaging: ^15.2.6
  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.2.1
  timeago: ^3.7.1
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: true